### ISSUE TITLE
error building master: package directories don't exist

### ISSUE THREAD

**Issue by jjakob** [bitcoin-core/HWI#587] opened 2022-03-11 12:51 UTC
needs this patch to build
```
--- a/setup.py
+++ b/setup.py
@@ -4,10 +4,13 @@
 packages = \
 ['hwilib',
  'hwilib.devices',
- 'hwilib.devices.btchip',
  'hwilib.devices.ckcc',
+ 'hwilib.devices.jadepy',
+ 'hwilib.devices.ledger_bitcoin',
+ 'hwilib.devices.ledger_bitcoin.btchip',
+ 'hwilib.devices.ledger_bitcoin.exception',
+ 'hwilib.devices.ledger_bitcoin.ledgercomm',
  'hwilib.devices.trezorlib',
- 'hwilib.devices.trezorlib.messages',
  'hwilib.devices.trezorlib.transport']

 package_data = \
```

**Comment by prusnak** [comment] 2022-03-11 13:06
Duplicate of https://github.com/bitcoin-core/HWI/pull/577

**Comment by achow101** [comment] 2022-03-15 16:39
Should be resolved now that setup.py was regenerated for the next release.

**Closed** 2022-03-15 16:38 UTC
