### ISSUE TITLE
dependency to typing_extensions

### ISSUE THREAD

**Issue by k9ert** [bitcoin-core/HWI#660] opened 2023-02-12 11:26 UTC
In specter, we're currently using hwilib `2.1.1`. We'll soon update to the next version. However with a new PR we currently get this dependency conflict:
```
  typing-extensions<4.0,>=3.7 (from hwi==2.1.1->-r requirements.in (line 11))
```
So i tried to figure out where that dependency is coming from and how to upgrade it but i'm struggling to properly install/build the project and run the tests or even figure out where that dependency is defined and why.
In pyproject.toml, i found:
```
[tool.poetry.dependencies]
...
typing-extensions = "^3.7"
```
In poetry.lock i found:
```
[package.dependencies]
typing-extensions = ">=3.7.4"
...
[package.dependencies]
typing-extensions = {version = ">=3.6.4", markers = "python_version < \"3.8\""}
...
[package.dependencies]
mypy-extensions = ">=0.4.3"
tomli = {version = ">=1.1.0", markers = "python_version < \"3.11\""}
typed-ast = {version = ">=1.4.0,<2", markers = "python_version < \"3.8\""}
typing-extensions = ">=3.10"
...
[[package]]
name = "typing-extensions"
version = "3.10.0.2"
description = "Backported and Experimental Type Hints for Python 3.5+"
category = "main"
optional = false
python-versions = "*"
...
typing-extensions = [
    {file = "typing_extensions-3.10.0.2-py2-none-any.whl", hash = "sha256:d8226d10bc02a29bcc81df19a26e56a9647f8b0a6d4a83924139f4a8b01f17b7"},
    {file = "typing_extensions-3.10.0.2-py3-none-any.whl", hash = "sha256:f1d25edafde516b146ecd0613dabcc61409817af4766fbbcfb8d1ad4ec441a34"},
    {file = "typing_extensions-3.10.0.2.tar.gz", hash = "sha256:49f75d16ff11f1cd258e1b988ccff82a3ca5570217d7ad8c5f48205dd99a677e"},
]
```
in setup.py i've found:
```
 'typing-extensions>=3.7,<4.0']
```
So why exactly is the package pinned? Any chance to get to `4.x` ? I'll probably like to have `4.1` in the midterm.

**Comment by prusnak** [comment] 2023-02-12 11:29
Essentially a duplicate of https://github.com/bitcoin-core/HWI/issues/572

**Closed** 2023-02-12 11:35 UTC
